import test from 'node:test';
import assert from 'node:assert/strict';
import {EvolutionWorld,ANCESTOR,LIMITS,TRAITS} from '../src/evolution.js';

test('the starting population is asexual prokaryote-like cells with copied founder genomes',()=>{const a=new EvolutionWorld({seed:4}),b=new EvolutionWorld({seed:4});assert.equal(a.cells.length,48);assert.deepEqual(a.cells,b.cells);assert.ok(a.cells.every(c=>c.parent===null&&c.branch===1));assert.deepEqual(a.cells[0].genome,ANCESTOR);assert.equal(TRAITS.length,8);});
test('binary fission creates daughters from one parent and passes the genome unchanged when mutation is off',()=>{const w=new EvolutionWorld({seed:8,mutation:0,capacity:180});for(let i=0;i<30;i++)w.step();assert.ok(w.divisions>0);const daughter=w.cells.find(c=>c.parent!==null);assert.ok(daughter);assert.ok(w.cells.some(c=>c.id===daughter.parent)||daughter.parent>0);assert.deepEqual(daughter.genome,ANCESTOR);});
test('replication mutations are small, heritable, and bounded by trait biology',()=>{const w=new EvolutionWorld({seed:21,mutation:1,capacity:180});for(let i=0;i<110;i++)w.step();assert.ok(w.divisions>20);assert.ok(w.cells.some(c=>c.genome.some((v,i)=>v!==ANCESTOR[i])));for(const c of w.cells)for(let i=0;i<c.genome.length;i++)assert.ok(c.genome[i]>=LIMITS[i][0]&&c.genome[i]<=LIMITS[i][1]);});
test('light-harvesting cells gain fitness only where sunlight is available',()=>{const low=new EvolutionWorld({seed:2,sunlight:0}),bright=new EvolutionWorld({seed:2,sunlight:1});const cell={genome:[...ANCESTOR]};cell.genome[2]=.9;assert.ok(bright.fitness(cell)>low.fitness(cell));});
test('adhesion allows a lineage of dividing cells to remain in a colony',()=>{const w=new EvolutionWorld({seed:14,mutation:0,capacity:180});for(const c of w.cells)c.genome[3]=.95;for(let i=0;i<70;i++)w.step();const colony=new Map();for(const c of w.cells){if(c.genome[3]>.68)colony.set(c.colony,(colony.get(c.colony)||0)+1);}assert.ok([...colony.values()].some(n=>n>=4));});
test('harsh conditions reduce reproductive success compared with a favorable vent',()=>{const calm=new EvolutionWorld({seed:6,nutrients:.8,temperature:.68,ultraviolet:.05}),harsh=new EvolutionWorld({seed:6,nutrients:.15,temperature:.08,ultraviolet:.95});const g={...calm.cells[0],genome:[...ANCESTOR]};assert.ok(calm.fitness(g)>harsh.fitness(g));});
