import {Walker,evaluate,DEFAULT_POLICY} from './physics.js';
import {Renderer,drawChart} from './render.js';
import {validateCheckpoint} from './policy.js';
const $=id=>document.getElementById(id),renderer=new Renderer($('scene'));
const missions=[{name:'Meadow mix-up',buddy:'Mochi',description:'Mochi took a wrong turn. Help Pip carry this fluffy friend over the little bumps.',terrain:.5,cargo:.8,goal:3.2},{name:'The little hill',buddy:'Pudding',description:'Pudding is a little heavier, and the hills are bumpier. A little practice goes a long way.',terrain:1,cargo:1.4,goal:3.6},{name:'Cloud camp',buddy:'Bean',description:'One last friend, one longer trail. Teach Pip to handle this extra-bumpy home stretch.',terrain:1.4,cargo:2,goal:4}];
let level=0,options,walker,best=[...DEFAULT_POLICY],starter=[...DEFAULT_POLICY],worker,ready=false,busy=false,training=false,mode='idle',history=[],generation=0,last=0,accumulator=0,practiceDelay=0,sound=false,audio,progress={unlocked:0,scores:[0,0,0]},loaded=false;
try{const p=JSON.parse(localStorage.getItem('peep-progress-v1'));if(p&&Number.isInteger(p.unlocked)&&p.unlocked>=0&&p.unlocked<3&&Array.isArray(p.scores)&&p.scores.length===3&&p.scores.every(x=>Number.isInteger(x)&&x>=0&&x<=3))progress=p;}catch{}
function settings(){return{target:1.1,assist:.8,population:40,seed:42+level,steps:720,...missions[level]};}
function beep(success=false){if(!sound)return;try{audio??=new AudioContext();audio.resume();const o=audio.createOscillator(),g=audio.createGain();o.type='sine';o.frequency.setValueAtTime(success?523:392,audio.currentTime);o.frequency.exponentialRampToValueAtTime(success?784:523,audio.currentTime+.15);g.gain.setValueAtTime(.06,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.3);o.connect(g);g.connect(audio.destination);o.start();o.stop(audio.currentTime+.31);}catch{}}
function notice(t){$('notice').textContent=t;}
function score(){ $('rescues').textContent=progress.scores.filter(x=>x>0).length;$('stars').textContent=progress.scores.reduce((a,b)=>a+b,0);document.querySelectorAll('[data-level]').forEach(b=>{const i=Number(b.dataset.level);b.disabled=i>progress.unlocked;b.classList.toggle('selected',i===level);const small=b.querySelector('small');if(small)small.textContent=i>progress.unlocked?'Locked':progress.scores[i]?'★'.repeat(progress.scores[i]):'Ready';});}
function bubble(title,text){$('bubble').querySelector('b').textContent=title;$('bubble').querySelector('span').textContent=text;}
function replay(){walker=new Walker(best,options);renderer.camera=0;practiceDelay=0;accumulator=0;}
function metrics(){const r=evaluate(best,options);$('generation').textContent=`${generation} rounds`;$('reward').textContent=r.reward.toFixed(1);$('distance').textContent=`${r.distance.toFixed(2)} m`;drawChart($('chart'),history);$('chart-caption').textContent=history.length?`${history.length} measured rounds · ${r.rescued?'rescue-capable':'still learning this trail'}`:'A starter skill — ready to try.';}
function request(){if(training&&ready&&!busy){busy=true;worker.postMessage({type:'generation'});}}
function makeWorker(){worker?.terminate();ready=false;busy=false;worker=new Worker(new URL('./worker.js',import.meta.url),{type:'module'});worker.onmessage=({data})=>{if(data.type==='ready'){ready=true;request();}else if(data.type==='progress')$('progress').value=data.candidate/data.total*100;else if(data.type==='generation'){busy=false;best=data.policy;generation=data.row.generation;history.push(data.row);$('progress').value=100;metrics();if(mode==='practice')replay();setTimeout(request,40);}else if(data.type==='error'){stopPractice();notice(`Practice stopped: ${data.message}`);}};worker.onerror=e=>{stopPractice();notice(`Practice could not start: ${e.message}`);};worker.postMessage({type:'init',options:{...options,initialPolicy:best}});}
function stopPractice(){training=false;$('train').textContent='✦ Practise & learn';if(mode==='practice'){mode='idle';$('mode-label').textContent='Practice paused';} }
function setLevel(i){stopPractice();level=i;options=settings();renderer.mission=i;mode='idle';history=[];generation=0;$('result').hidden=true;$('pause').textContent='Pause Ⅱ';$('level-title').textContent=missions[i].name;$('level-description').textContent=missions[i].description;$('mission-label').textContent=`0${i+1} / ${missions[i].name.toUpperCase()}`;$('buddy-name').textContent=`${missions[i].buddy} needs you!`;$('cargo-label').textContent=`Passenger load: ${missions[i].cargo.toFixed(1)} model units`;$('mode-label').textContent='Ready when you are!';bubble("Hi! I'm Pip.",`Let's bring ${missions[i].buddy} home.`);replay();metrics();score();makeWorker();}
function play(){stopPractice();if(busy){worker.terminate();makeWorker();}mode='playing';$('result').hidden=true;$('pause').textContent='Pause Ⅱ';$('mode-label').textContent='On a rescue!';bubble('Here we go!',`First, find ${missions[level].buddy}.`);replay();beep();}
function finish(success){mode='result';$('result').hidden=false;$('result-icon').textContent=success?'★ ★ ★':'♡';$('result-title').textContent=success?'A friend is home!':'A little wobble!';if(success){const stars=walker.t<3?3:walker.t<5?2:1;progress.scores[level]=Math.max(progress.scores[level],stars);progress.unlocked=Math.max(progress.unlocked,Math.min(2,level+1));try{localStorage.setItem('peep-progress-v1',JSON.stringify(progress));}catch{}score();$('result-icon').textContent='★'.repeat(stars);$('result-text').textContent=`${missions[level].buddy} is safe! ${walker.t.toFixed(1)} seconds · ${stars} ${stars===1?'star':'stars'} earned. ${level===2?'All three friends are home.':'The next adventure is unlocked.'}`;$('result-action').textContent=level<2?'Next adventure →':'Play again ↻';$('result-action').onclick=()=>{if(level<2)setLevel(level+1);play();};beep(true);}else{$('result-text').textContent='No worries — your friend is okay. Practise the course to help Pip find a steadier gait, then try again.';$('result-action').textContent='Try again →';$('result-action').onclick=play;}$('mode-label').textContent=success?'Rescue complete!':'Try a little practice';}
$('play').onclick=play;$('train').onclick=()=>{if(training){stopPractice();return;}if(mode==='playing'||mode==='paused'){mode='idle';replay();}mode='practice';$('result').hidden=true;training=true;$('train').textContent='Ⅱ Pause practice';$('mode-label').textContent='Learning by trying';bubble('Practice makes progress.','Testing new gaits for this exact course.');notice('Real reward-based training. Each round tests 40 controllers, including the best so far.');request();};$('pause').onclick=()=>{if(mode==='playing'){mode='paused';$('pause').textContent='Resume ▶';$('mode-label').textContent='Taking a breather';}else if(mode==='paused'){mode='playing';$('pause').textContent='Pause Ⅱ';}};
$('sound').onclick=()=>{sound=!sound;$('sound').textContent=sound?'Sound on ♫':'Sound off ♫';$('sound').setAttribute('aria-pressed',String(sound));beep();};document.querySelectorAll('[data-level]').forEach(b=>b.onclick=()=>setLevel(Number(b.dataset.level)));
function checkpoint(){return{version:3,environment:'robot-rescue-v1',algorithm:'cem',generation,policy:best,options,history};}
$('export').onclick=()=>{const u=URL.createObjectURL(new Blob([JSON.stringify(checkpoint(),null,2)],{type:'application/json'})),a=document.createElement('a');a.href=u;a.download='pip-rescue-skill.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);notice('Pip’s skill is saved.');};$('import').onclick=()=>$('policy-file').click();$('policy-file').onchange=async e=>{try{const f=e.target.files[0];if(!f)return;if(f.size>100000)throw Error('File is too large.');const c=validateCheckpoint(JSON.parse(await f.text()));stopPractice();best=[...c.policy];generation=c.generation;history=c.history??[];mode='idle';$('result').hidden=true;replay();metrics();makeWorker();notice('Loaded skill. It will be evaluated on your selected course.');}catch(err){notice(`Could not load skill: ${err.message}`);}finally{e.target.value='';}};
$('demo').onclick=()=>{best=[...starter];setLevel(level);notice('Starter skill restored.');};
function animate(t){if(!last)last=t;accumulator+=Math.min((t-last)/1000,.06);last=t;while(accumulator>=1/120){if(mode==='playing'||mode==='practice'){if(walker.fallen||walker.rescued||walker.t>=6){if(mode==='playing')finish(walker.rescued);else{practiceDelay+=1/120;if(practiceDelay>.8){replay();break;}}}else{const carried=walker.carrying;walker.step();if(!carried&&walker.carrying&&mode==='playing'){bubble('Got you, little friend!','The passenger adds weight. Next stop: camp!');beep();}}}accumulator-=1/120;}renderer.draw(walker);$('rollout-state').textContent=mode==='playing'||mode==='paused'?`${walker.carrying?'Friend aboard ♡':'Find your friend'} · ${Math.max(0,options.goal-walker.nodes[0].x).toFixed(1)} m to camp`:'Find friend → Carry gently → Reach camp';requestAnimationFrame(animate);}
window.addEventListener('resize',()=>drawChart($('chart'),history));$('play').disabled=true;setLevel(0);requestAnimationFrame(animate);
try{const r=await fetch('./trained-example.json');if(!r.ok)throw Error(`HTTP ${r.status}`);const c=validateCheckpoint(await r.json());starter=[...c.policy];best=[...starter];loaded=true;setLevel(0);notice('Pip has a starter skill. Practice can adapt it to each new course.');}catch(e){notice('Starter skill unavailable. Use Practice to teach Pip a gait.');}finally{$('play').disabled=false;}
