import {EvolutionWorld,TRAITS,LABELS,LIMITS} from './evolution.js';
import {CellRenderer,drawChart} from './render.js';
const $=id=>document.getElementById(id),initial={seed:173,nutrients:.72,sunlight:.18,temperature:.72,ultraviolet:.12,mutation:.035,capacity:180};
let world=new EvolutionWorld(initial),running=false,seeking=false,speed=10000,chartMode='fitness',last=0,accum=0,eventCount=0,selected=null,seekToken=0;
const renderer=new CellRenderer($('world'),world);
function environmentalLabels(readControls=true){if(readControls){world.settings.nutrients=+$('nutrients').value;world.settings.sunlight=+$('sunlight').value;world.settings.temperature=+$('temperature').value;world.settings.ultraviolet=+$('ultraviolet').value;world.settings.mutation=+$('mutation').value;world.recordSettings();}else for(const id of ['nutrients','sunlight','temperature','ultraviolet','mutation'])$(id).value=world.settings[id];$('nutrients-value').textContent=world.settings.nutrients<.35?'Scarce':world.settings.nutrients<.7?'Moderate':'Abundant';$('sunlight-value').textContent=world.settings.sunlight<.25?'Dim':world.settings.sunlight<.65?'Filtered':'Bright';$('temperature-value').textContent=world.settings.temperature<.35?'Cool sea':world.settings.temperature<.72?'Warm vents':'Hot vents';$('ultraviolet-value').textContent=world.settings.ultraviolet<.2?'Shielded':world.settings.ultraviolet<.6?'Exposed':'Intense';$('mutation-value').textContent=`${(world.settings.mutation*100).toFixed(1)}%`;}
function renderTraits(){const cells=world.cells;if(!cells.length){$('trait-list').innerHTML='';return;}const means=world.summary().means;const names=LABELS;const values=means.map((v,i)=>i===7?(v-.5):v);$('trait-list').innerHTML=names.map((name,i)=>{const[lo,hi]=LIMITS[i],v=means[i],width=clampPercent((v-lo)/(hi-lo));const display=i===7?`${v.toFixed(2)} relative units`:`${Math.round(v*100)}%`;return `<div class="trait"><span>${name}</span><b>${display}</b><i><u style="width:${width}%"></u></i></div>`;}).join('');}
function selectedCell(){if(selected===null)return null;return world.cells.find(c=>c.id===selected)||null;}
function inspect(){const c=selectedCell();if(!c){$('cell-title').textContent='The founding population';$('cell-copy').textContent='Primitive cells in a mineral-rich seep. No nucleus. No oxygen. Each daughter cell receives a copied genome.';return;}const g=c.genome;$('cell-title').textContent=`Cell #${c.id} · branch ${c.branch}`;$('cell-copy').textContent=`${g[3]>.68?'Adhesive cell · colony-capable':'Free-living prokaryote-like cell'} · ${c.age} model generations old · ${c.division} observed divisions. Parent #${c.parent??'founder'}. DNA is inherited asexually with replication errors.`;}
function setMilestones(){const map=[['flagella',0],['phototrophy',1],['colony',2],['complex',3]];for(const[key,i]of map){const el=document.querySelectorAll('.milestone')[i];el.classList.toggle('active',world.milestones[key]);}}
function showEvent(){if(world.events.length>eventCount){const e=world.events.at(-1);if(e.type==='branch'){$('event-log').innerHTML=`<span>LINEAGE BRANCH · GEN ${e.generation}</span><p>A heritable change in ${e.trait.toLowerCase()} begins a divergent branch.</p>`;}else if(e.type==='milestone'){$('event-log').innerHTML=`<span>EVOLUTIONARY OBSERVATION · GEN ${e.generation}</span><p>${e.message}</p>`;}else if(e.type==='extinction'){$('event-log').innerHTML='<span>EXTINCTION</span><p>This sample lost its last cell. Reset the origin and try different planetary conditions.</p>';running=false;}eventCount=world.events.length;}}
function update(){const s=world.summary();$('population').textContent=s.population;if(!seeking&&document.activeElement!==$('time-slider'))$('time-slider').value=Math.min(+$('time-slider').max,s.generation);$('generation').textContent=s.generation.toLocaleString();$('species').textContent=s.branches;$('divisions').textContent=s.divisions.toLocaleString();const before=Math.max(0,3800-world.time/1e6);$('earth-age').textContent=before.toLocaleString('en',{minimumFractionDigits:2,maximumFractionDigits:2});$('time-readout').textContent=`${(world.time/1e6).toFixed(3)} Myr elapsed`;$('world-state').textContent=running?'CELL DIVISION · SELECTION ACTIVE':s.population?'PAUSED · FIRST CELLS':'EXTINCTION';$('toggle').textContent=running?'Pause the world Ⅱ':'Start the experiment ▶';$('toggle').setAttribute('aria-pressed',String(running));$('epoch').textContent=world.milestones.phototrophy?'LIGHT-HARVESTING CELLS · OXYGEN NOT MODELLED':'HYDROTHERMAL SEEP · OXYGEN-POOR MODEL';$('hint');showEvent();renderTraits();inspect();setMilestones();drawChart($('chart'),world.history,chartMode);}
function clampPercent(x){return Math.max(2,Math.min(100,Math.round(x*100)));}
$('toggle').onclick=()=>{if(!world.cells.length)return;if(running)accum=0;running=!running;world.paused=!running;update();};$('reset').onclick=()=>{world=new EvolutionWorld({...initial,nutrients:+$('nutrients').value,sunlight:+$('sunlight').value,temperature:+$('temperature').value,ultraviolet:+$('ultraviolet').value,mutation:+$('mutation').value});renderer.world=world;running=false;selected=null;eventCount=0;environmentalLabels(false);slider.value=0;$('seek-status').textContent='Drag to choose a moment';update();};
for(const id of ['nutrients','sunlight','temperature','ultraviolet','mutation'])$(id).addEventListener('input',()=>{environmentalLabels();});
const slider=$('time-slider');slider.addEventListener('input',()=>{const gen=+slider.value;$('time-readout').textContent=`${(gen*.00025).toFixed(3)} Myr elapsed`;$('seek-status').textContent=`Release to seek · generation ${gen.toLocaleString()}`;});slider.addEventListener('change',()=>seekTo(+slider.value));
function seekTo(target){target=Math.max(0,Math.min(+slider.max,Math.floor(target)));running=false;accum=0;world.paused=true;$('toggle').disabled=true;slider.disabled=true;for(const id of ['nutrients','sunlight','temperature','ultraviolet','mutation'])$(id).disabled=true;const token=++seekToken,backward=target<world.generation;let replay=null;if(backward){replay=world.createReplay(target);world=replay.world;renderer.world=world;selected=null;eventCount=0;}seeking=true;world.paused=false;$('seek-status').textContent=`Seeking to ${(target*.00025).toFixed(3)} Myr…`;const runChunk=()=>{if(token!==seekToken)return;let n=0,done=false;if(replay){done=replay.advance(300);}else{while(n<300&&world.generation<target&&world.cells.length){world.paused=false;world.step();n++;}done=world.generation>=target||!world.cells.length;}$('seek-status').textContent=`Seeking ${(world.time/1e6).toFixed(3)} / ${(target*.00025).toFixed(3)} Myr`;update();if(done){world.paused=true;running=false;seeking=false;$('toggle').disabled=false;slider.disabled=false;for(const id of ['nutrients','sunlight','temperature','ultraviolet','mutation'])$(id).disabled=false;slider.value=world.generation;environmentalLabels(false);$('seek-status').textContent=`At ${(world.time/1e6).toFixed(3)} Myr`;update();}else requestAnimationFrame(runChunk);};requestAnimationFrame(runChunk);}

document.querySelectorAll('[data-speed]').forEach(b=>b.addEventListener('click',()=>{speed=+b.dataset.speed;accum=0;document.querySelectorAll('[data-speed]').forEach(x=>x.classList.toggle('chosen',x===b));}));
document.querySelectorAll('[data-chart]').forEach(b=>b.addEventListener('click',()=>{chartMode=b.dataset.chart;document.querySelectorAll('[data-chart]').forEach(x=>x.classList.toggle('selected',x===b));drawChart($('chart'),world.history,chartMode);}));
$('help').onclick=()=>{const d=document.querySelector('details');d.open=!d.open;if(d.open)d.scrollIntoView({behavior:'smooth',block:'center'});};
$('world').addEventListener('click',e=>{const r=$('world').getBoundingClientRect(),x=(e.clientX-r.left)*720/r.width,y=(e.clientY-r.top)*600/r.height;let best=null,dist=24;for(const c of world.cells){const d=Math.hypot(c.x-x,c.y-y);if(d<dist){dist=d;best=c;}}selected=best?.id??null;update();});
function frame(t){if(!last)last=t;const elapsed=Math.min(.06,(t-last)/1000);last=t;if(running){accum+=elapsed*speed;let n=0;const budget=speed>=100000?2400:speed>=10000?600:22;while(accum>=1&&n<budget){world.step();accum--;n++;}if(n)update();}renderer.draw(selected);requestAnimationFrame(frame);}
environmentalLabels();update();requestAnimationFrame(frame);
