export const TRAITS=['enzyme','motility','phototrophy','adhesion','thermotolerance','uvShield','repair','cellSize'];
export const LABELS=['Mineral enzymes','Motility','Light harvesting','Cell adhesion','Heat tolerance','UV protection','DNA repair','Cell size'];
export const LIMITS=[[0,1],[0,1],[0,1],[0,1],[0,1],[0,1],[0,1],[.5,1.5]];
export const ANCESTOR=[.3,.03,.02,.04,.65,.12,.25,.72];
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
export function random(seed=173){let s=seed>>>0;return()=>{s+=0x6D2B79F5;let t=s;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296;};}
export class EvolutionWorld{
 constructor({seed=173,nutrients=.72,sunlight=.18,temperature=.72,ultraviolet=.12,mutation=.035,capacity=180}={}){this.settings={seed,nutrients,sunlight,temperature,ultraviolet,mutation,capacity};this.rng=random(seed);this.time=0;this.generation=0;this.nextId=1;this.nextBranch=2;this.divisions=0;this.deaths=0;this.cells=[];this.branches=[{id:1,parent:null,genome:[...ANCESTOR],born:0}];this.events=[];this.history=[];this.lastSnapshot=0;this.milestones={flagella:false,phototrophy:false,colony:false,complex:false};this.makeCells(48);this.snapshot();}
 makeCells(n){for(let i=0;i<n;i++){const a=this.rng()*Math.PI*2,r=22+this.rng()*83;this.cells.push(this.newCell(ANCESTOR,365+Math.cos(a)*r,294+Math.sin(a)*r,1));}}
 newCell(genome,x,y,branch=1,parent=null,colony=null){return{id:this.nextId++,genome:[...genome],x,y,heading:this.rng()*Math.PI*2,age:0,branch,parent,colony:colony??this.nextId,division:0,bornAt:this.generation};}
 mutate(genome){const child=[...genome],changed=[];for(let i=0;i<child.length;i++){if(this.rng()<this.settings.mutation){const[a,b]=LIMITS[i],sd=(b-a)*.075;child[i]=clamp(child[i]+(this.rng()+this.rng()+this.rng()+this.rng()-2)*sd*1.7,a,b);changed.push(i);}}return{genome:child,changed};}
 fitness(cell,colonySize=1){const g=cell.genome,s=this.settings;const minerals=s.nutrients*(.18+.82*g[0]),light=s.sunlight*g[2]*.9;const energy=minerals+light;const demand=.15+g[7]*.13+g[1]*.055+g[3]*.035;const tempStress=Math.max(0,Math.abs(s.temperature-(.24+.68*g[4]))-.12)*.3;const radiation=s.ultraviolet*(1-g[5])*.28*(1-g[6]*.28);const collectiveShield=colonySize>=3?g[3]*Math.min(1,(colonySize-2)/5)*s.ultraviolet*.18:0;return clamp(.76+energy*.34-demand-tempStress-radiation+collectiveShield,.015,1.3);}
 step(){if(this.paused)return;const r=this.rng,s=this.settings;this.generation++;this.time+=250;const born=[],dead=[],colonyCounts=new Map();for(const cell of this.cells)colonyCounts.set(cell.colony,(colonyCounts.get(cell.colony)||0)+1);for(const c of this.cells){c.age++;c.heading+=(r()-.5)*(.12+c.genome[1]*.28);const drift=c.genome[1]*1.7;c.x=clamp(c.x+Math.cos(c.heading)*drift+r()*1.2-.6,26,704);c.y=clamp(c.y+Math.sin(c.heading)*drift+r()*1.2-.6,38,548);const fit=this.fitness(c,colonyCounts.get(c.colony)||1),stress=Math.max(0,.44-fit);const deathChance=.035+stress*.35+(c.age>45?.08:0)+(c.age>70?.4:0);if(r()<deathChance){dead.push(c);continue;}const divisionChance=.06+fit*.18;if(r()<divisionChance&&this.cells.length+born.length<s.capacity){const{genome,changed}=this.mutate(c.genome);let branch=c.branch;const difference=changed.reduce((sum,i)=>sum+Math.abs(genome[i]-c.genome[i])/(LIMITS[i][1]-LIMITS[i][0]),0);if(changed.length>=2&&difference>.075&&r()<.12&&this.branches.length<500){branch=this.nextBranch++;this.branches.push({id:branch,parent:c.branch,genome:[...genome],born:this.generation});this.events.push({type:'branch',branch,trait:LABELS[changed[0]],generation:this.generation});}const colony=genome[3]>.58&&r()<.78?c.colony:this.nextId+this.cells.length+born.length;born.push(this.newCell(genome,c.x+(r()-.5)*10,c.y+(r()-.5)*10,branch,c.id,colony));c.division++;this.divisions++;}}
 if(dead.length){const gone=new Set(dead.map(c=>c.id));this.cells=this.cells.filter(c=>!gone.has(c.id));this.deaths+=dead.length;}this.cells.push(...born);
 // At carrying capacity, differential reproductive success displaces the least-fit cells.
 if(this.cells.length>s.capacity){this.cells.sort((a,b)=>this.fitness(a)-this.fitness(b));this.cells.splice(0,this.cells.length-s.capacity);}
 this.detectMilestones();if(this.cells.length&&this.generation-this.lastSnapshot>=8)this.snapshot();if(!this.cells.length){this.events.push({type:'extinction',generation:this.generation});this.paused=true;}}
 detectMilestones(){const avg=i=>this.cells.reduce((a,c)=>a+c.genome[i],0)/Math.max(1,this.cells.length);const branches=[['flagella',avg(1)>.32,'Motile cells appear in the sample.'],['phototrophy',avg(2)>.38,'Light-harvesting pigments become common.'],['colony',this.cells.some(c=>c.genome[3]>.68&&(this.cells.filter(x=>x.colony===c.colony).length>=4)),'A persistent cell colony forms.'],['complex',avg(3)>.82&&avg(1)>.55&&avg(6)>.52,'Cooperation and motility coexist in the population.']];for(const[k,yes,message]of branches)if(yes&&!this.milestones[k]){this.milestones[k]=true;this.events.push({type:'milestone',key:k,message,generation:this.generation});}}
 snapshot(){if(!this.cells.length)return;const avg=i=>this.cells.reduce((a,c)=>a+c.genome[i],0)/this.cells.length;this.history.push({generation:this.generation,years:this.time,population:this.cells.length,fitness:+(this.cells.reduce((a,c)=>a+this.fitness(c),0)/this.cells.length).toFixed(3),motility:+avg(1).toFixed(3),phototrophy:+avg(2).toFixed(3),adhesion:+avg(3).toFixed(3),branches:this.branches.length,divisions:this.divisions});this.history=this.history.slice(-300);this.lastSnapshot=this.generation;}
 reset(){const opts={...this.settings};return new EvolutionWorld(opts);}
 summary(){const n=this.cells.length,avg=i=>n?this.cells.reduce((a,c)=>a+c.genome[i],0)/n:0;return{population:n,generation:this.generation,divisions:this.divisions,deaths:this.deaths,branches:this.branches.length,means:TRAITS.map((_,i)=>avg(i)),time:this.time,milestones:{...this.milestones}};}
}
