export const TRAITS=['body','legs','legLength','speed','senses','efficiency','hue','lifespan'];
export const LIMITS=[[.15,.48],[2,6],[.45,1.4],[.45,2.6],[55,225],[.45,1.65],[0,360],[42,170]];
export function random(seed=42){let s=seed>>>0;return()=>{s+=0x6D2B79F5;let t=s;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296;};}
const clamp=(x,a,b)=>Math.max(a,Math.min(b,x));
export const START_GENOME=[.3,4,.85,1.25,120,1,142,100];
export class EvolutionWorld{
 constructor({seed=74,food=.75,temperature=.85,hazard=.15,mutation=.14,capacity=180}={}){this.settings={seed,food,temperature,hazard,mutation,capacity};this.rng=random(seed);this.time=0;this.generation=0;this.nextId=1;this.dead=0;this.deaths={predation:0,starvation:0,oldAge:0};this.totalBirths=0;this.maxGeneration=0;this.events=[];this.history=[];this.lastSnapshot=0;this.extinctionNoted=false;this.foods=[];this.creatures=[];this.makeHabitat();for(let i=0;i<32;i++)this.creatures.push(this.spawn(this.seedGenome(i),55+this.rng()*890,65+this.rng()*450,4.2,this.rng));}
 seedGenome(i){const g=[...START_GENOME];g[6]=(116+i*13)%360;g[1]=2+(i%5);g[2]=.58+(i%4)*.19;g[3]=.7+(i%6)*.2;g[4]=75+(i%7)*17;g[5]=.58+(i%4)*.23;g[0]=.19+(i%5)*.045;g[7]=65+(i%6)*13;return g;}
 makeHabitat(){this.foods=[];const r=this.rng;for(let i=0;i<20;i++){const x=65+(i%5)*220+(r()-.5)*70,y=75+Math.floor(i/5)*145+(r()-.5)*48;this.foods.push({x,y,amount:4+r()*3,max:7});}this.puddles=Array.from({length:6},()=>({x:80+this.rng()*840,y:65+this.rng()*460,rx:24+this.rng()*45,ry:10+this.rng()*24}));this.bushes=Array.from({length:15},()=>({x:25+this.rng()*950,y:25+this.rng()*550,s:.7+this.rng()*.8}));}
 spawn(genome,x,y,energy=3,r=this.rng,parent=0,generation=0){return{id:this.nextId++,genome:[...genome],x,y,vx:0,vy:0,energy,age:0,heading:r()*Math.PI*2,phase:r()*Math.PI*2,parent,generation,children:0,born:this.time,alive:true};}
 mutate(a,b){const r=this.rng,rate=this.settings.mutation;this.lastMutationTrait=null;const child=a.map((v,i)=>{let q=r()<.5?v:b[i];if(r()<rate){const[a0,a1]=LIMITS[i],sd=(a1-a0)*(i===6?.09:.07);q+=((r()+r()+r()+r()-2)*sd*1.55);if(this.lastMutationTrait===null)this.lastMutationTrait=TRAITS[i];}return clamp(q,...LIMITS[i]);});child[1]=clamp(Math.round(child[1]),2,6);child[6]=(child[6]+360)%360;return child;}
 foodAt(x,y){let best=null,d2=Infinity;for(const f of this.foods)if(f.amount>.08){const dx=f.x-x,dy=f.y-y,z=dx*dx+dy*dy;if(z<d2){d2=z;best=f;}}return best?{food:best,distance:Math.sqrt(d2)}:null;}
 step(){if(this.paused)return;const r=this.rng,dt=.1,s=this.settings;this.time+=dt;const tempPenalty=Math.abs(Math.log(Math.max(.1,s.temperature)/.85));for(const f of this.foods)f.amount=Math.min(f.max,f.amount+(.009*s.food)*dt*10);const newborn=[];
 for(const c of this.creatures){if(!c.alive)continue;const g=c.genome,size=g[0],legs=g[1],eff=g[5],sense=g[4],target=this.foodAt(c.x,c.y);c.age+=dt;c.phase+=dt*(2.4+g[3]*1.2);let dx=0,dy=0;
 if(target&&target.distance<sense*1.5){dx=(target.food.x-c.x)/Math.max(1,target.distance);dy=(target.food.y-c.y)/Math.max(1,target.distance);}else{c.heading+=(r()-.5)*.32;dx=Math.cos(c.heading);dy=Math.sin(c.heading);}
 const thirst=target&&target.distance<15;const pace=g[3]*(.78+g[2]*.25)*(thirst?.38:1);c.vx=.78*c.vx+.22*(dx*pace*22);c.vy=.78*c.vy+.22*(dy*pace*22);c.x=clamp(c.x+c.vx*dt+Math.sin(c.phase)*.15,13,987);c.y=clamp(c.y+c.vy*dt,16,584);if(Math.abs(c.vx)+Math.abs(c.vy)>.4)c.heading=Math.atan2(c.vy,c.vx);
 const traveled=Math.hypot(c.vx,c.vy)*dt;const thermal=1+tempPenalty*(size<.27?.45:size>.39?.55:.2);c.energy-=dt*(.012*(.6+size*2+legs*.1)*(1.65-eff*.55)*thermal+traveled*.00048+pace*.00032);
 if(target&&target.distance<15&&target.food.amount>.08){const bite=Math.min(.2,target.food.amount);target.food.amount-=bite;c.energy=Math.min(4.8+size*7,c.energy+bite*6.3);}
 const predatorExposure=s.hazard*dt*.003*(1.05-g[3]/3.6)*(.55+(1-eff)*.15);if(r()<Math.max(0,predatorExposure)){c.alive=false;c.death='predation';this.dead++;this.deaths.predation++;this.events.push({type:'lost',name:this.name(c),reason:'a hungry fox',x:c.x,y:c.y});if(this.events.length>80)this.events.shift();continue;}
 if(c.energy<=0||c.age>g[7]){c.alive=false;c.death=c.energy<=0?'starvation':'oldAge';this.deaths[c.death]++;this.dead++;continue;}
 if(c.age>8&&c.energy>6.25+size*1.4&&this.creatures.length+newborn.length<s.capacity&&r()<dt*(.34+eff*.18)){const mate=this.findMate(c);if(mate){const baby=this.spawn(this.mutate(g,mate.genome),c.x+(r()-.5)*23,c.y+(r()-.5)*23,3.5,r,c.id,Math.max(c.generation,mate.generation)+1);newborn.push(baby);c.energy-=1.7;mate.energy-=1.35;c.children++;mate.children++;this.totalBirths++;const trait=this.changedTrait(baby.genome,g);if(this.lastMutationTrait&&r()<.55)this.events.push({type:'mutation',name:this.name(baby),trait:this.lastMutationTrait,x:baby.x,y:baby.y});if(this.events.length>80)this.events.shift();}}
 }
 this.creatures.push(...newborn);this.creatures=this.creatures.filter(c=>c.alive);if(this.creatures.length===0&&!this.extinctionNoted){this.extinctionNoted=true;this.events.push({type:'extinct',name:'',reason:'No one survived this climate. Try warmer weather or more plants.'});}if(this.creatures.length&&this.time-this.lastSnapshot>=4)this.snapshot();}
 findMate(c){let best=null,d2=74**2;for(const b of this.creatures)if(b!==c&&b.alive&&b.age>8&&b.energy>5){const dx=b.x-c.x,dy=b.y-c.y,d=dx*dx+dy*dy;if(d<d2){d2=d;best=b;}}return best;}
 changedTrait(g,old){const i=g.findIndex((v,j)=>v!==old[j]);return TRAITS[i<0?0:i];}
 name(c){return ['Pip','Mallow','Sprout','Pebble','Mochi','Button','Clover','Noodle'][c.id%8];}
 snapshot(){const p=this.creatures,avg=i=>p.reduce((s,c)=>s+c.genome[i],0)/p.length;this.maxGeneration=Math.max(this.maxGeneration,...p.map(c=>c.generation));const row={generation:this.maxGeneration,time:+this.time.toFixed(1),population:p.length,meanLegs:+avg(1).toFixed(2),meanSpeed:+avg(3).toFixed(2),meanBody:+avg(0).toFixed(3),births:this.totalBirths,dead:this.dead};this.history.push(row);this.history=this.history.slice(-240);this.generation=this.maxGeneration;this.lastSnapshot=this.time;}
 rewild(){for(let i=0;i<8;i++){const g=this.mutate(START_GENOME,this.seedGenome(i));this.creatures.push(this.spawn(g,80+this.rng()*840,70+this.rng()*450,4.2,this.rng));}this.extinctionNoted=false;this.events.push({type:'release',name:'',reason:'Eight little pioneers joined the habitat.'});}
 summary(){const p=this.creatures;if(!p.length)return{population:0,generation:this.maxGeneration,meanLegs:0,meanSpeed:0,meanLifespan:0,oldest:0,births:this.totalBirths,dead:this.dead,deaths:{...this.deaths},plants:Math.round(this.foods.reduce((a,b)=>a+b.amount,0))};const avg=i=>p.reduce((s,c)=>s+c.genome[i],0)/p.length;return{population:p.length,generation:this.maxGeneration,meanLegs:avg(1),meanSpeed:avg(3),meanLifespan:avg(7),oldest:Math.max(...p.map(c=>c.age)),births:this.totalBirths,dead:this.dead,deaths:{...this.deaths},plants:Math.round(this.foods.reduce((a,b)=>a+b.amount,0))};}
}
