const lerp=(a,b,t)=>a.map((v,i)=>v+(b[i]-v)*t);
export class Renderer{
 constructor(canvas){this.canvas=canvas;this.ctx=canvas.getContext('2d');this.muscles=true;this.side=false;this.camera=0;}
 size(){const r=this.canvas.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);if(this.canvas.width!==Math.round(r.width*d)||this.canvas.height!==Math.round(r.height*d)){this.canvas.width=Math.round(r.width*d);this.canvas.height=Math.round(r.height*d);}this.ctx.setTransform(d,0,0,d,0,0);this.w=r.width;this.h=r.height;this.scale=Math.min(this.w*.33,this.h*.33);}
 project([x,y,z]){x-=this.camera;const yaw=this.side?0:.55,rx=x*Math.cos(yaw)-z*Math.sin(yaw),depth=x*Math.sin(yaw)+z*Math.cos(yaw),factor=1/(1+depth*.07);return[this.w*.55+rx*this.scale*factor,this.h*.72-y*this.scale*factor+depth*this.scale*.22];}
 line(a,b,color,width){const c=this.ctx,A=this.project(a),B=this.project(b);c.beginPath();c.moveTo(...A);c.lineTo(...B);c.strokeStyle=color;c.lineWidth=width;c.lineCap='round';c.stroke();}
 ball(p,r,color){const c=this.ctx,[x,y]=this.project(p);c.beginPath();c.arc(x,y,r,0,Math.PI*2);const g=c.createRadialGradient(x-r*.3,y-r*.4,r*.1,x,y,r);g.addColorStop(0,'#fcf9e9');g.addColorStop(.6,color);g.addColorStop(1,'#7b8277');c.fillStyle=g;c.fill();}
 muscle(a,b,color,width){const c=this.ctx,A=this.project(lerp(a,b,.1)),B=this.project(lerp(a,b,.9)),dx=B[0]-A[0],dy=B[1]-A[1],l=Math.hypot(dx,dy)||1,n=[-dy/l*width,dx/l*width],M=[(A[0]+B[0])/2,(A[1]+B[1])/2];c.beginPath();c.moveTo(...A);c.quadraticCurveTo(M[0]+n[0],M[1]+n[1],...B);c.quadraticCurveTo(M[0]-n[0],M[1]-n[1],...A);c.fillStyle=color;c.fill();this.line(lerp(a,b,.02),lerp(a,b,.13),'#ebe6cf',1.8);this.line(lerp(a,b,.87),b,'#ebe6cf',1.8);}
 draw(walker){this.size();const c=this.ctx,W=this.w,H=this.h;this.camera+=.04*(walker.nodes[0].x-this.camera);c.clearRect(0,0,W,H);const bg=c.createLinearGradient(0,0,0,H);bg.addColorStop(0,'#e3e6e0');bg.addColorStop(1,'#c9cfc5');c.fillStyle=bg;c.fillRect(0,0,W,H);
 const center=Math.floor(this.camera);for(let i=center-10;i<center+12;i++)for(let j=-9;j<12;j++){const a=this.project([i*.5,0,j*.5]),b=this.project([(i+1)*.5,0,j*.5]),d=this.project([(i+1)*.5,0,(j+1)*.5]),e=this.project([i*.5,0,(j+1)*.5]);c.beginPath();c.moveTo(...a);c.lineTo(...b);c.lineTo(...d);c.lineTo(...e);c.closePath();c.fillStyle=(i+j)%2?'#bfc8bb40':'#eef1e83a';c.fill();c.strokeStyle='#9eaa9b24';c.lineWidth=.5;c.stroke();}
 const n=walker.nodes,hip=[n[0].x,n[0].y,0],chest=[n[1].x,n[1].y,0],dir=[chest[0]-hip[0],chest[1]-hip[1],0];const neck=[chest[0]+dir[0]*.17,chest[1]+dir[1]*.17,0],head=[neck[0]+dir[0]*.25,neck[1]+dir[1]*.25,0];
 const shadow=this.project([hip[0],0,0]);c.save();c.translate(...shadow);c.scale(1,.3);c.beginPath();c.ellipse(5,0,this.scale*.3,this.scale*.13,0,0,Math.PI*2);c.fillStyle='#56664d24';c.fill();c.restore();
 const bone='#ece7d4',joint='#c4c7b1',phase=walker.t*walker.policy[0]*Math.PI*2;
 const drawLeg=side=>{const z=side===0?-.13:.13,A=[...hip];A[2]=z;const K=[n[2+side*2].x,n[2+side*2].y,z],F=[n[3+side*2].x,n[3+side*2].y,z],T=[F[0]+.13,F[1]-.01,z];this.line(A,K,'#7e897b',8);this.line(A,K,bone,5);this.line(K,F,'#7e897b',6);this.line(K,F,bone,3.5);const shin=[...K];shin[2]+=.035;const ankle=[...F];ankle[2]+=.035;this.line(shin,ankle,bone,2);this.line(F,T,bone,4);if(this.muscles){const activation=(Math.sin(phase+side*Math.PI)+1)/2;this.muscle(A,K,side===0?`rgba(137,49,82,${.65+.3*activation})`:`rgba(164,61,77,${.65+.3*activation})`,this.scale*.055);this.muscle(lerp(K,F,.16),F,'#635489',this.scale*.033);}this.ball(K,this.scale*.025,joint);this.ball(F,this.scale*.019,joint);if(walker.contacts[side]){const p=this.project([F[0],.005,z]);c.beginPath();c.ellipse(...p,13,4,0,0,Math.PI*2);c.fillStyle='#4d9a6740';c.fill();}};
 drawLeg(0);this.line([hip[0],hip[1],-.14],[hip[0],hip[1],.14],bone,10);this.line(hip,chest,'#6c7b6b',5);for(let t=.08;t<1;t+=.1)this.ball(lerp(hip,chest,t),this.scale*.013,bone);
 const torsoPoint=(t,z)=>{const p=lerp(hip,chest,t);p[2]=z;return p;};for(let i=0;i<7;i++){const t=.48+i*.075,z=.15*Math.sin((i+2)/10*Math.PI);for(const s of[-1,1]){this.line(torsoPoint(t,0),torsoPoint(t-.065,s*z),bone,2.2);this.line(torsoPoint(t-.065,s*z),torsoPoint(t-.16,s*z*.7),bone,1.5);}}
 if(this.muscles){for(const s of[-1,1]){this.muscle(torsoPoint(.2,s*.08),torsoPoint(.93,s*.075),'#775988',this.scale*.027);this.muscle(torsoPoint(.1,s*.08),torsoPoint(.36,s*.055),'#a34358',this.scale*.032);}}
 for(const side of[0,1]){const s=side===0?-1:1,sw=Math.sin(phase+side*Math.PI)*.28,shoulder=torsoPoint(.98,s*.21),elbow=[shoulder[0]+sw,shoulder[1]-.28,s*.27],hand=[elbow[0]+.16,elbow[1]-.2,s*.29];this.line(chest,shoulder,bone,3);this.line(shoulder,elbow,bone,4);this.line(elbow,hand,bone,3);if(this.muscles){this.muscle(shoulder,elbow,s<0?'#76558e':'#a63e58',this.scale*.032);this.muscle(elbow,hand,'#76558e',this.scale*.024);}this.ball(shoulder,this.scale*.024,joint);this.ball(elbow,this.scale*.018,joint);for(let i=0;i<4;i++)this.line(hand,[hand[0]+.035+i*.014,hand[1]-.05,s*.29+i*.008],bone,1.2);}
 drawLeg(1);this.line(chest,neck,bone,4);this.ball(head,this.scale*.065,bone);const jaw=[head[0]+.018,head[1]-.064,head[2]];this.ball(jaw,this.scale*.036,bone);const eye=this.project([head[0]+.041,head[1]+.005,head[2]+.045]);c.fillStyle='#555f51';c.beginPath();c.ellipse(...eye,3,3.8,0,0,Math.PI*2);c.fill();
 if(walker.assist>0){const a=this.project(hip),b=this.project([hip[0],hip[1]+.18,0]);c.setLineDash([3,4]);c.strokeStyle='#377e6799';c.lineWidth=1.5;c.beginPath();c.moveTo(...a);c.lineTo(...b);c.stroke();c.setLineDash([]);c.fillStyle='#377e67';c.font='9px system-ui';c.fillText('↑ support',a[0]+10,a[1]-10);}
 c.fillStyle='#60745e66';c.font='11px system-ui';c.fillText('PLANAR PHYSICS / ANATOMICAL OVERLAY',24,65);}
}
export function drawChart(canvas,history){const r=canvas.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);canvas.width=Math.round(r.width*d);canvas.height=Math.round(r.height*d);const c=canvas.getContext('2d');c.scale(d,d);const W=r.width,H=r.height,L=38,B=23,T=10;const values=history.flatMap(h=>[h.best,h.mean]),lo=values.length?Math.floor(Math.min(...values)-1):-2,hi=values.length?Math.ceil(Math.max(...values)+1):2;const y=v=>T+(hi-v)/(hi-lo)*(H-T-B),x=i=>L+i/Math.max(1,history.length-1)*(W-L-10);c.font='9px system-ui';for(let i=0;i<5;i++){const v=lo+(hi-lo)*i/4,Y=y(v);c.strokeStyle='#2a3931';c.beginPath();c.moveTo(L,Y);c.lineTo(W,Y);c.stroke();c.fillStyle='#7c9284';c.fillText(v.toFixed(1),0,Y+3);}if(!history.length){c.fillStyle='#7c9284';c.fillText('Rewards will appear here as the controller learns.',L+12,H/2);return;}for(const[key,color]of[['mean','#647e91'],['best','#93e7ad']]){c.beginPath();history.forEach((h,i)=>i?c.lineTo(x(i),y(h[key])):c.moveTo(x(i),y(h[key])));c.strokeStyle=color;c.lineWidth=key==='best'?2:1.5;c.stroke();if(history.length===1){c.beginPath();c.arc(x(0),y(history[0][key]),3,0,Math.PI*2);c.fillStyle=color;c.fill();}}c.fillStyle='#7c9284';c.fillText('1',L,H-3);c.fillText(`Generation ${history.length}`,Math.max(L,W-85),H-3);}
