const rgba=(h,a=1)=>`hsla(${h},43%,49%,${a})`;
export class GardenRenderer{
 constructor(canvas,world,onSelect){this.canvas=canvas;this.c=canvas.getContext('2d');this.world=world;this.onSelect=onSelect;this.scale=1;this.offX=0;this.offY=0;this.pointer=0;canvas.addEventListener('click',e=>{const r=canvas.getBoundingClientRect(),x=(e.clientX-r.left-this.offX)/this.scale,y=(e.clientY-r.top-this.offY)/this.scale;let pick=null,d=32;for(const a of this.world.creatures){const z=Math.hypot(a.x-x,a.y-y);if(z<d){d=z;pick=a;}}if(pick)this.onSelect(pick);});}
 resize(){const r=this.canvas.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);if(this.canvas.width!==Math.round(r.width*d)||this.canvas.height!==Math.round(r.height*d)){this.canvas.width=Math.round(r.width*d);this.canvas.height=Math.round(r.height*d);}this.c.setTransform(d,0,0,d,0,0);this.scale=Math.min(r.width/1000,r.height/600);this.viewW=r.width/this.scale;this.offX=(r.width-this.viewW*this.scale)/2;this.offY=(r.height-600*this.scale)/2;this.c.translate(this.offX,this.offY);this.c.scale(this.scale,this.scale);this.w=this.viewW;this.h=600;}
 blossom(x,y,s,hue,amount=1){const c=this.c,n=Math.min(7,Math.max(2,Math.ceil(amount)));c.save();c.translate(x,y);c.strokeStyle='#7a9c6b';c.lineWidth=2;c.beginPath();c.moveTo(0,9);c.quadraticCurveTo(-2,1,0,-9);c.stroke();for(let j=0;j<n;j++){const a=j*Math.PI*2/n;c.fillStyle=j%2?'#f3d590':'#efb9a9';c.beginPath();c.ellipse(Math.cos(a)*5,Math.sin(a)*5,3.5,2.5,a,0,Math.PI*2);c.fill();}c.fillStyle=rgba(hue);c.beginPath();c.arc(0,0,3,0,Math.PI*2);c.fill();c.restore();}
 creature(a,selected=false){const c=this.c,g=a.genome,s=g[0],legs=g[1],len=g[2],size=9+s*17,reach=8+len*8,phase=a.phase,heading=a.heading;const cos=Math.cos(heading),sin=Math.sin(heading),xx=(u,v)=>[a.x+u*cos-v*sin,a.y+u*sin+v*cos];c.save();c.translate(a.x,a.y);c.rotate(heading);c.fillStyle='#67755722';c.beginPath();c.ellipse(1,5,size*1.35,size*.86,0,0,Math.PI*2);c.fill();
 for(let i=0;i<legs;i++){const side=i%2?1:-1,row=Math.floor(i/2),spread=(row-(Math.ceil(legs/2)-1)/2)*6.3,ax=spread*.5,ay=side*size*.53,endX=ax+(row%2?1:-1)*reach*.55+Math.sin(phase+row)*2,endY=side*(size*.8+reach*.57);c.strokeStyle='#537961';c.lineWidth=1.8+s*4;c.lineCap='round';c.beginPath();c.moveTo(ax,ay);c.quadraticCurveTo(ax+(row%2?1:-1)*reach*.6,ay+side*2,endX,endY);c.stroke();c.fillStyle='#f4d59a';c.beginPath();c.arc(endX,endY,1.7+s*2,0,Math.PI*2);c.fill();}
 c.fillStyle=rgba(g[6]);c.beginPath();c.ellipse(-size*.42,0,size*.83,size*.68,.04,0,Math.PI*2);c.fill();c.fillStyle=`hsla(${g[6]},48%,63%,.88)`;c.beginPath();c.ellipse(size*.34,0,size*.48,size*.43,.08,0,Math.PI*2);c.fill();c.strokeStyle='rgba(255,255,255,.45)';c.lineWidth=1;c.beginPath();c.arc(-size*.42,0,size*.54,-1.6,1.35);c.stroke();
 for(const side of[-1,1]){c.strokeStyle='#587b62';c.lineWidth=1.35;c.beginPath();c.moveTo(size*.6,side*size*.12);c.quadraticCurveTo(size*.98,side*size*.46+Math.sin(phase)*2,size*1.14,side*size*.3);c.stroke();c.fillStyle='#fff9dc';c.beginPath();c.arc(size*.21,side*size*.2,2.2+s*1.8,0,Math.PI*2);c.fill();c.fillStyle='#364c48';c.beginPath();c.arc(size*.25,side*size*.2,1.1+s*.8,0,Math.PI*2);c.fill();}
 c.fillStyle='#ffe6a8aa';c.beginPath();c.ellipse(-size*.28,-size*.2,size*.2,size*.12,0,0,Math.PI*2);c.fill();if(selected){c.strokeStyle='#fff7cf';c.lineWidth=2;c.setLineDash([4,3]);c.beginPath();c.ellipse(0,0,size*1.7,size*1.62,0,0,Math.PI*2);c.stroke();c.setLineDash([]);}c.restore();}
 draw(selectedId=null){this.resize();const c=this.c,w=this.world,t=w.time;if(this.follow){const target=this.world.creatures.find(a=>a.id===this.follow);if(target)this.cameraX+=(target.x-this.cameraX- this.w*.5)*.06;}else this.cameraX*=.96;const pan=this.cameraX?this.cameraX:0;c.clearRect(0,0,this.w,640);c.save();c.translate(-pan,0);const sky=c.createLinearGradient(0,0,0,600);sky.addColorStop(0,'#d9eee3');sky.addColorStop(.64,'#edf0d7');sky.addColorStop(1,'#dae7bd');c.fillStyle=sky;c.fillRect(0,0,1000,600);
 for(let i=0;i<5;i++){const x=((i*247-t*1.2)%1250+1250)%1250-120,y=72+(i%3)*48;c.fillStyle='#fffdf27d';c.beginPath();c.ellipse(x,y,47,13,0,0,Math.PI*2);c.ellipse(x-14,y-7,18,17,0,0,Math.PI*2);c.ellipse(x+12,y-5,24,20,0,0,Math.PI*2);c.fill();}
 c.fillStyle='#b9d8bd';c.beginPath();c.moveTo(0,302);c.bezierCurveTo(180,237,288,332,470,281);c.bezierCurveTo(686,214,822,273,1000,237);c.lineTo(1000,600);c.lineTo(0,600);c.fill();c.fillStyle='#d9e4b9';c.beginPath();c.moveTo(0,369);c.bezierCurveTo(182,325,267,407,460,357);c.bezierCurveTo(668,307,813,367,1000,324);c.lineTo(1000,600);c.lineTo(0,600);c.fill();c.fillStyle='#e8e6c9';c.fillRect(0,440,1000,160);
 for(const b of w.bushes){const hue=108+b.s*9;c.fillStyle=`hsla(${hue},27%,53%,.7)`;for(const[dx,dy,r]of[[0,0,10],[-8,3,7],[9,4,8],[2,-7,7]]){c.beginPath();c.arc(b.x+dx*b.s,b.y+dy*b.s,r*b.s,0,Math.PI*2);c.fill();}}
 for(const p of w.puddles){c.fillStyle='#a6d4cf';c.beginPath();c.ellipse(p.x,p.y,p.rx,p.ry,-.1,0,Math.PI*2);c.fill();c.strokeStyle='#fffdf499';c.lineWidth=2;c.beginPath();c.ellipse(p.x-4,p.y-2,p.rx*.62,p.ry*.36,-.1,3.5,5.8);c.stroke();}
 for(let i=0;i<35;i++){const x=(i*97+31)%1000,y=455+((i*61)%140);c.strokeStyle=i%2?'#9cb586':'#aebc8e';c.lineWidth=1.3;c.beginPath();c.moveTo(x,y+4);c.lineTo(x-2,y);c.moveTo(x,y+4);c.lineTo(x+3,y-2);c.stroke();}
 for(const f of w.foods){if(f.amount<.14)continue;const n=Math.ceil(f.amount*1.5);for(let i=0;i<n;i++){const a=i*2.399,r=5+Math.sqrt(i)*6;this.blossom(f.x+Math.cos(a)*r,f.y+Math.sin(a)*r,1,w.bushes[i%w.bushes.length].s*130,f.amount);}}
 if(w.settings.hazard>.025){const fx=25+((t*13)%950),fy=84+Math.sin(t*.065)*22;c.save();c.translate(fx,fy);c.fillStyle='#d98d71';c.beginPath();c.ellipse(0,0,16,9,0,0,Math.PI*2);c.fill();c.beginPath();c.arc(11,-7,7,0,Math.PI*2);c.fill();c.fillStyle='#d98d71';for(const side of[-1,1]){c.beginPath();c.moveTo(7,-11);c.lineTo(8,-19);c.lineTo(13,-12);c.fill();}c.fillStyle='#fff9e8';c.beginPath();c.arc(14,-8,2.3,0,Math.PI*2);c.fill();c.fillStyle='#394c41';c.beginPath();c.arc(15,-8,1,0,Math.PI*2);c.fill();c.restore();}
 const sorted=[...w.creatures].sort((a,b)=>a.y-b.y);for(const a of sorted)this.creature(a,a.id===selectedId);
 c.fillStyle='#668473';c.font='11px system-ui';c.fillText('A little patch of the big, wide world',18,579);c.restore();}
}
export function drawPortrait(canvas,g){const d=Math.min(devicePixelRatio||1,2),r=canvas.getBoundingClientRect();canvas.width=Math.max(1,Math.round(r.width*d));canvas.height=Math.max(1,Math.round(r.height*d));const c=canvas.getContext('2d');c.scale(d,d);const x=r.width/2,y=r.height/2,s=Math.min(r.width,r.height)*.22,h=g[6];c.fillStyle='#f1f0df';c.beginPath();c.arc(x,y,s*2.7,0,Math.PI*2);c.fill();c.save();c.translate(x,y);c.fillStyle=rgba(h);c.beginPath();c.ellipse(-s*.3,0,s*1.25,s*.8,0,0,Math.PI*2);c.fill();c.fillStyle=`hsla(${h},48%,64%,.9)`;c.beginPath();c.arc(s*.85,0,s*.65,0,Math.PI*2);c.fill();c.fillStyle='#fffbeb';for(const side of[-1,1]){c.beginPath();c.arc(s*.9,side*s*.24,s*.16,0,Math.PI*2);c.fill();c.fillStyle='#354e47';c.beginPath();c.arc(s*.94,side*s*.24,s*.09,0,Math.PI*2);c.fill();c.fillStyle='#fffbeb';}for(let i=0;i<g[1];i++){const a=i*Math.PI*2/g[1],ex=Math.cos(a)*s*1.65,ey=Math.sin(a)*s*1.1;c.beginPath();c.moveTo(0,0);c.lineTo(ex,ey);c.strokeStyle='#58816a';c.lineWidth=2;c.stroke();}c.restore();}
export function drawChart(canvas,history,mode='population'){const r=canvas.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);canvas.width=Math.round(r.width*d);canvas.height=Math.round(r.height*d);const c=canvas.getContext('2d');c.scale(d,d);const W=r.width,H=r.height,L=32,R=8,T=12,B=20;let field=mode==='population'?'population':mode==='legs'?'meanLegs':'meanSpeed';if(!history.length){c.fillStyle='#93a28f';c.font='10px system-ui';c.fillText('The family story will appear here.',L,H/2);return;}let vals=history.map(x=>x[field]),min=Math.min(...vals),max=Math.max(...vals);if(min===max){min=Math.max(0,min-1);max+=1;}const y=v=>T+(max-v)/(max-min)*(H-T-B),x=i=>L+i/Math.max(1,history.length-1)*(W-L-R);for(let j=0;j<4;j++){const yy=T+j*(H-T-B)/3;c.strokeStyle='#edf0e6';c.beginPath();c.moveTo(L,yy);c.lineTo(W-R,yy);c.stroke();c.fillStyle='#a1ad98';c.font='8px system-ui';c.fillText((max-(max-min)*j/3).toFixed(mode==='population'?0:1),0,yy+3);}c.beginPath();history.forEach((v,i)=>i?c.lineTo(x(i),y(v[field])):c.moveTo(x(i),y(v[field])));c.strokeStyle='#4b9576';c.lineWidth=2;c.stroke();c.fillStyle='#7e9d7c';c.font='8px system-ui';c.fillText(`Generation ${history[0].generation}`,L,H-4);c.textAlign='right';c.fillText(`Generation ${history.at(-1).generation}`,W,H-4);c.textAlign='left';}
